# -*- coding: utf-8 -*-
"""project model .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXnp6e_dPrBndn5juMxv-sZBMKPJBxth
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import joblib

df=pd.read_csv('/content/diabetes (1).csv')
  df.head()

df.describe()

df.info()

df.isnull().sum()

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier()
model.fit(X_train, y_train)

joblib.dump(model, "model.pkl")
print(" Model trained and saved as model.pkl")

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

import pickle
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

new_data = np.array([[6, 148, 72, 35, 0, 33.6, 0.627, 50]])
prediction = model.predict(new_data)
print("Predicted Outcome:", "Diabetic" if prediction[0]==1 else "Non-Diabetic")

from google.colab import files
files.download('model.pkl')

